GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTM1OTE3NzZ9.DR_nJO6MCh_g3k5-FuLfYO_UHS1fF_RByuIC3mMeqXw



###

POST http://localhost:3000/auth

Content-Type: application/json
{
    "username": "Rahma"
}
